title: Jinbao
author: Jinbao
email: jinbaosite@163.com


menus:
  - title: 首页
    url: /
  - title: 机器学习
    url: /ml
  - title: 深度学习
    url: /dl
  - title: LLM
    url: /llm
  - title: 推荐算法
    url: /recsys
  - title: Agent
    url: /agent
  - title: 项目
    url: /projects
  - title: 关于
    url: /about

theme: jekyll-theme-cayman
markdown: kramdown
